package webservice.cn.ebao.blog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.8
 * 2016-03-17T19:10:34.730+08:00
 * Generated source version: 3.0.8
 * 
 */
@WebService(targetNamespace = "http://www.e-bao.cn/", name = "blogHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BlogHttpGet {

    @WebResult(name = "string", targetNamespace = "http://www.e-bao.cn/", partName = "Body")
    @WebMethod(operationName = "GetBlog")
    public java.lang.String getBlog(
        @WebParam(partName = "flag", name = "flag", targetNamespace = "http://www.e-bao.cn/")
        java.lang.String flag
    );

    @WebResult(name = "string", targetNamespace = "http://www.e-bao.cn/", partName = "Body")
    @WebMethod(operationName = "HelloWorld")
    public java.lang.String helloWorld();
}
